[build]
  command = "pnpm install --frozen-lockfile && pnpm run build"
  publish = ".output/public"

[functions]
  directory = ".output/server"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server"
  status = 200
