[build]
  command = "npm run build"
  publish = ".output/public"

[functions]
  directory = ".output/server/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server"
  status = 200
